
[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board =  esp32-s3-devkitc-1
framework = arduino
board_build.partitions = default_8MB.csv

monitor_speed = 115200
upload_speed = 460800
build_type = debug
build_flags = -D DEBUG
lib_deps = 
	avinabmalla/ESP32_BleSerial@^3.0.0

[env:esp32c3-dev]
platform = espressif32
board = dfrobot_beetle_esp32c3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_type = debug
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D DEBUG
lib_deps = 
	avinabmalla/ESP32_BleSerial@^3.0.0
